sonar.projectKey=Cohort-9-MERN-Notes-App
sonar.projectName=Cohort 9 MERN Notes App
sonar.projectVersion=1.0.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8